// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: internal/v1/internal.proto

package internalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clock         *VectorClock           `protobuf:"bytes,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_internal_v1_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_v1_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_internal_v1_internal_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetClock() *VectorClock {
	if x != nil {
		return x.Clock
	}
	return nil
}

func (x *PublishRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PublishRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_internal_v1_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_v1_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_internal_v1_internal_proto_rawDescGZIP(), []int{1}
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_internal_v1_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_v1_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_internal_v1_internal_proto_rawDescGZIP(), []int{2}
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clock         *VectorClock           `protobuf:"bytes,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_internal_v1_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_v1_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_internal_v1_internal_proto_rawDescGZIP(), []int{3}
}

func (x *AckResponse) GetClock() *VectorClock {
	if x != nil {
		return x.Clock
	}
	return nil
}

func (x *AckResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type VectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clock         map[uint64]uint64      `protobuf:"bytes,1,rep,name=clock,proto3" json:"clock,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_internal_v1_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_v1_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_internal_v1_internal_proto_rawDescGZIP(), []int{4}
}

func (x *VectorClock) GetClock() map[uint64]uint64 {
	if x != nil {
		return x.Clock
	}
	return nil
}

var File_internal_v1_internal_proto protoreflect.FileDescriptor

const file_internal_v1_internal_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/v1/internal.proto\x12\binternal\"c\n" +
	"\x0ePublishRequest\x12+\n" +
	"\x05clock\x18\x01 \x01(\v2\x15.internal.VectorClockR\x05clock\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x11\n" +
	"\x0fPublishResponse\"\f\n" +
	"\n" +
	"AckRequest\"L\n" +
	"\vAckResponse\x12+\n" +
	"\x05clock\x18\x01 \x01(\v2\x15.internal.VectorClockR\x05clock\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x7f\n" +
	"\vVectorClock\x126\n" +
	"\x05clock\x18\x01 \x03(\v2 .internal.VectorClock.ClockEntryR\x05clock\x1a8\n" +
	"\n" +
	"ClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x012\x82\x01\n" +
	"\bInternal\x12@\n" +
	"\aPublish\x12\x18.internal.PublishRequest\x1a\x19.internal.PublishResponse\"\x00\x124\n" +
	"\x03Ack\x12\x14.internal.AckRequest\x1a\x15.internal.AckResponse\"\x00B>Z<github.com/WadeCappa/consensus/gen/go/internal/v1;internalpbb\x06proto3"

var (
	file_internal_v1_internal_proto_rawDescOnce sync.Once
	file_internal_v1_internal_proto_rawDescData []byte
)

func file_internal_v1_internal_proto_rawDescGZIP() []byte {
	file_internal_v1_internal_proto_rawDescOnce.Do(func() {
		file_internal_v1_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_v1_internal_proto_rawDesc), len(file_internal_v1_internal_proto_rawDesc)))
	})
	return file_internal_v1_internal_proto_rawDescData
}

var file_internal_v1_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_v1_internal_proto_goTypes = []any{
	(*PublishRequest)(nil),  // 0: internal.PublishRequest
	(*PublishResponse)(nil), // 1: internal.PublishResponse
	(*AckRequest)(nil),      // 2: internal.AckRequest
	(*AckResponse)(nil),     // 3: internal.AckResponse
	(*VectorClock)(nil),     // 4: internal.VectorClock
	nil,                     // 5: internal.VectorClock.ClockEntry
}
var file_internal_v1_internal_proto_depIdxs = []int32{
	4, // 0: internal.PublishRequest.clock:type_name -> internal.VectorClock
	4, // 1: internal.AckResponse.clock:type_name -> internal.VectorClock
	5, // 2: internal.VectorClock.clock:type_name -> internal.VectorClock.ClockEntry
	0, // 3: internal.Internal.Publish:input_type -> internal.PublishRequest
	2, // 4: internal.Internal.Ack:input_type -> internal.AckRequest
	1, // 5: internal.Internal.Publish:output_type -> internal.PublishResponse
	3, // 6: internal.Internal.Ack:output_type -> internal.AckResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_v1_internal_proto_init() }
func file_internal_v1_internal_proto_init() {
	if File_internal_v1_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_v1_internal_proto_rawDesc), len(file_internal_v1_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_v1_internal_proto_goTypes,
		DependencyIndexes: file_internal_v1_internal_proto_depIdxs,
		MessageInfos:      file_internal_v1_internal_proto_msgTypes,
	}.Build()
	File_internal_v1_internal_proto = out.File
	file_internal_v1_internal_proto_goTypes = nil
	file_internal_v1_internal_proto_depIdxs = nil
}
