// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: kvstore/v1/kvstore.proto

package kvstorepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Update        []byte                 `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_kvstore_v1_kvstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_v1_kvstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetUpdate() []byte {
	if x != nil {
		return x.Update
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_kvstore_v1_kvstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_v1_kvstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{1}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_kvstore_v1_kvstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_v1_kvstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Data                []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	NodeId              uint64                 `protobuf:"varint,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Version             uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	WriteTimeUnixMillis uint64                 `protobuf:"varint,4,opt,name=writeTimeUnixMillis,proto3" json:"writeTimeUnixMillis,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_kvstore_v1_kvstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_v1_kvstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetResponse) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *GetResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetResponse) GetWriteTimeUnixMillis() uint64 {
	if x != nil {
		return x.WriteTimeUnixMillis
	}
	return 0
}

var File_kvstore_v1_kvstore_proto protoreflect.FileDescriptor

const file_kvstore_v1_kvstore_proto_rawDesc = "" +
	"\n" +
	"\x18kvstore/v1/kvstore.proto\x12\akvstore\"6\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06update\x18\x02 \x01(\fR\x06update\"\r\n" +
	"\vPutResponse\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x85\x01\n" +
	"\vGetResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06nodeId\x18\x02 \x01(\x04R\x06nodeId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x120\n" +
	"\x13writeTimeUnixMillis\x18\x04 \x01(\x04R\x13writeTimeUnixMillis2s\n" +
	"\akvstore\x122\n" +
	"\x03Put\x12\x13.kvstore.PutRequest\x1a\x14.kvstore.PutResponse\"\x00\x124\n" +
	"\x03Get\x12\x13.kvstore.GetRequest\x1a\x14.kvstore.GetResponse\"\x000\x01B<Z:github.com/WadeCappa/consensus/pkg/go/kvstore/v1;kvstorepbb\x06proto3"

var (
	file_kvstore_v1_kvstore_proto_rawDescOnce sync.Once
	file_kvstore_v1_kvstore_proto_rawDescData []byte
)

func file_kvstore_v1_kvstore_proto_rawDescGZIP() []byte {
	file_kvstore_v1_kvstore_proto_rawDescOnce.Do(func() {
		file_kvstore_v1_kvstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kvstore_v1_kvstore_proto_rawDesc), len(file_kvstore_v1_kvstore_proto_rawDesc)))
	})
	return file_kvstore_v1_kvstore_proto_rawDescData
}

var file_kvstore_v1_kvstore_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kvstore_v1_kvstore_proto_goTypes = []any{
	(*PutRequest)(nil),  // 0: kvstore.PutRequest
	(*PutResponse)(nil), // 1: kvstore.PutResponse
	(*GetRequest)(nil),  // 2: kvstore.GetRequest
	(*GetResponse)(nil), // 3: kvstore.GetResponse
}
var file_kvstore_v1_kvstore_proto_depIdxs = []int32{
	0, // 0: kvstore.kvstore.Put:input_type -> kvstore.PutRequest
	2, // 1: kvstore.kvstore.Get:input_type -> kvstore.GetRequest
	1, // 2: kvstore.kvstore.Put:output_type -> kvstore.PutResponse
	3, // 3: kvstore.kvstore.Get:output_type -> kvstore.GetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kvstore_v1_kvstore_proto_init() }
func file_kvstore_v1_kvstore_proto_init() {
	if File_kvstore_v1_kvstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kvstore_v1_kvstore_proto_rawDesc), len(file_kvstore_v1_kvstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kvstore_v1_kvstore_proto_goTypes,
		DependencyIndexes: file_kvstore_v1_kvstore_proto_depIdxs,
		MessageInfos:      file_kvstore_v1_kvstore_proto_msgTypes,
	}.Build()
	File_kvstore_v1_kvstore_proto = out.File
	file_kvstore_v1_kvstore_proto_goTypes = nil
	file_kvstore_v1_kvstore_proto_depIdxs = nil
}
